services:
  turtlmap:
    build: .
    image: turtlmap:latest
    container_name: turtlmap-ct
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/catkin_ws/src/TURTLMap
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: /bin/bash
